version: '3.8'

services:

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
