apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: react-client:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: react-data
          mountPath: /path/to/react/data
      volumes:
      - name: react-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: react-client
spec:
  selector:
    app: react-client
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
